spring:
  application:
    name: product-management
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/product?characterEncoding=UTF-8&connectionCollation=utf8mb4_bin
    username: root
    password: root
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration

server:
  port: 8081
