spring:
  application:
    name: order-management
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?characterEncoding=UTF-8&connectionCollation=utf8mb4_bin
    username: root
    password: root
  jpa:
    show-sql: true
  flyway:
    locations: classpath:db/migration

feign:
  httpclient:
    enabled: true

service:
  product:
    url: http://127.0.0.1:8081
    name: product

server:
  port: 8080
